CREATE TABLE "media_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "sources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_type_id" integer NOT NULL,
  "name" varchar(200) NOT NULL,
  "url" varchar(255),
  "description" text
);

CREATE TABLE "entries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_id" integer NOT NULL,
  "title" varchar(200) NOT NULL,
  "description" text,
  "date_published" date,
  "location" varchar(200),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "craft" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text,
  "shape" varchar(50),
  "notes" text
);

CREATE TABLE "entry_craft" (
  "entry_id" integer,
  "craft_id" integer,
  PRIMARY KEY ("entry_id", "craft_id")
);

CREATE TABLE "people" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notes" text
);

CREATE TABLE "entry_people" (
  "entry_id" integer,
  "people_id" integer,
  PRIMARY KEY ("entry_id", "people_id")
);

ALTER TABLE "sources" ADD FOREIGN KEY ("media_type_id") REFERENCES "media_types" ("id") ON DELETE CASCADE;

ALTER TABLE "entries" ADD FOREIGN KEY ("source_id") REFERENCES "sources" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_craft" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_craft" ADD FOREIGN KEY ("craft_id") REFERENCES "craft" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_people" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_people" ADD FOREIGN KEY ("people_id") REFERENCES "people" ("id") ON DELETE CASCADE;
